{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "96ae17b4",
   "metadata": {},
   "source": [
    "**Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "Note: Here Exception class refers to the base class for all the exceptions.**\n",
    " \n",
    "In Python, exceptions are a way to handle errors and unexpected situations that might arise during the execution of a program. When standard built-in exceptions provided by Python's exception hierarchy (which is built upon the Exception class) are not sufficient to accurately represent the nature of an error in your code, you can create your own custom exceptions by subclassing the Exception class or its descendants. Let's delve into why we use the Exception class as a base when creating custom exceptions:\n",
    "\n",
    "- Consistency and Readability: By using the Exception class as the base for your custom exception, you ensure that your custom exception inherits common properties and behaviors shared by all exceptions in Python. This promotes consistency and readability when working with your custom exception in various parts of your code.\n",
    "\n",
    "- Hierarchy: The exception hierarchy in Python is designed to be structured and organized. The Exception class serves as a root for all exceptions, allowing you to create a hierarchy of custom exceptions based on the type of errors you want to represent. You can create more specialized exceptions that inherit from Exception to differentiate between different types of errors and handle them accordingly.\n",
    "\n",
    "- Catching and Handling: By having your custom exception inherit from the Exception class, you ensure that your custom exception is caught by generic exception-catching mechanisms. This makes it easier to handle your custom exception along with other exceptions in a unified way, simplifying error handling logic.\n",
    "\n",
    "- Clear Intent: When someone reads your code, seeing that you're subclassing Exception to create a custom exception makes it clear that your intention is to represent a specific type of error. This self-documenting approach helps other developers understand the purpose of the custom exception without having to look through the entire code."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fda0c6e1",
   "metadata": {},
   "source": [
    "**Q2. Write a python program to print Python Exception Hierarchy.**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5367f94c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def python_exception_hierarchy(exception_class,indent = 0):\n",
    "    print(' '*indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        python_exception_hierarchy(subclass,indent+1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "90dfd3d4",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      " TypeError\n",
      "  FloatOperation\n",
      "  MultipartConversionError\n",
      " StopAsyncIteration\n",
      " StopIteration\n",
      " ImportError\n",
      "  ModuleNotFoundError\n",
      "  ZipImportError\n",
      " OSError\n",
      "  ConnectionError\n",
      "   BrokenPipeError\n",
      "   ConnectionAbortedError\n",
      "   ConnectionRefusedError\n",
      "   ConnectionResetError\n",
      "    RemoteDisconnected\n",
      "  BlockingIOError\n",
      "  ChildProcessError\n",
      "  FileExistsError\n",
      "  FileNotFoundError\n",
      "  IsADirectoryError\n",
      "  NotADirectoryError\n",
      "  InterruptedError\n",
      "   InterruptedSystemCall\n",
      "  PermissionError\n",
      "  ProcessLookupError\n",
      "  TimeoutError\n",
      "  UnsupportedOperation\n",
      "  herror\n",
      "  gaierror\n",
      "  SSLError\n",
      "   SSLCertVerificationError\n",
      "   SSLZeroReturnError\n",
      "   SSLWantWriteError\n",
      "   SSLWantReadError\n",
      "   SSLSyscallError\n",
      "   SSLEOFError\n",
      "  Error\n",
      "   SameFileError\n",
      "  SpecialFileError\n",
      "  ExecError\n",
      "  ReadError\n",
      "  URLError\n",
      "   HTTPError\n",
      "   ContentTooShortError\n",
      "  BadGzipFile\n",
      " EOFError\n",
      "  IncompleteReadError\n",
      " RuntimeError\n",
      "  RecursionError\n",
      "  NotImplementedError\n",
      "   ZMQVersionError\n",
      "   StdinNotImplementedError\n",
      "  _DeadlockError\n",
      "  BrokenBarrierError\n",
      "  BrokenExecutor\n",
      "   BrokenThreadPool\n",
      "  SendfileNotAvailableError\n",
      "  ExtractionError\n",
      "  VariableError\n",
      " NameError\n",
      "  UnboundLocalError\n",
      " AttributeError\n",
      "  FrozenInstanceError\n",
      " SyntaxError\n",
      "  IndentationError\n",
      "   TabError\n",
      " LookupError\n",
      "  IndexError\n",
      "  KeyError\n",
      "   NoSuchKernel\n",
      "   UnknownBackend\n",
      "  CodecRegistryError\n",
      " ValueError\n",
      "  UnicodeError\n",
      "   UnicodeEncodeError\n",
      "   UnicodeDecodeError\n",
      "   UnicodeTranslateError\n",
      "  UnsupportedOperation\n",
      "  JSONDecodeError\n",
      "  SSLCertVerificationError\n",
      "  Error\n",
      "  UnsupportedDigestmodError\n",
      "  IllegalMonthError\n",
      "  IllegalWeekdayError\n",
      "  ParserError\n",
      "  ClassNotFound\n",
      "  ClipboardEmpty\n",
      "  MessageDefect\n",
      "   NoBoundaryInMultipartDefect\n",
      "   StartBoundaryNotFoundDefect\n",
      "   CloseBoundaryNotFoundDefect\n",
      "   FirstHeaderLineIsContinuationDefect\n",
      "   MisplacedEnvelopeHeaderDefect\n",
      "   MissingHeaderBodySeparatorDefect\n",
      "   MultipartInvariantViolationDefect\n",
      "   InvalidMultipartContentTransferEncodingDefect\n",
      "   UndecodableBytesDefect\n",
      "   InvalidBase64PaddingDefect\n",
      "   InvalidBase64CharactersDefect\n",
      "   InvalidBase64LengthDefect\n",
      "   HeaderDefect\n",
      "    InvalidHeaderDefect\n",
      "    HeaderMissingRequiredValue\n",
      "    NonPrintableDefect\n",
      "    ObsoleteHeaderDefect\n",
      "    NonASCIILocalPartDefect\n",
      "    InvalidDateDefect\n",
      "  MacroToEdit\n",
      "  InvalidFileException\n",
      "  UnequalIterablesError\n",
      "  InvalidVersion\n",
      "  _InvalidELFFileHeader\n",
      "  InvalidWheelFilename\n",
      "  InvalidSdistFilename\n",
      "  InvalidSpecifier\n",
      "  InvalidMarker\n",
      "  UndefinedComparison\n",
      "  UndefinedEnvironmentName\n",
      "  InvalidRequirement\n",
      "   RequirementParseError\n",
      "  InvalidVersion\n",
      " AssertionError\n",
      " ArithmeticError\n",
      "  FloatingPointError\n",
      "  OverflowError\n",
      "  ZeroDivisionError\n",
      "   DivisionByZero\n",
      "   DivisionUndefined\n",
      "  DecimalException\n",
      "   Clamped\n",
      "   Rounded\n",
      "    Underflow\n",
      "    Overflow\n",
      "   Inexact\n",
      "    Underflow\n",
      "    Overflow\n",
      "   Subnormal\n",
      "    Underflow\n",
      "   DivisionByZero\n",
      "   FloatOperation\n",
      "   InvalidOperation\n",
      "    ConversionSyntax\n",
      "    DivisionImpossible\n",
      "    DivisionUndefined\n",
      "    InvalidContext\n",
      " SystemError\n",
      "  CodecRegistryError\n",
      " ReferenceError\n",
      " MemoryError\n",
      " BufferError\n",
      " Warning\n",
      "  UserWarning\n",
      "   GetPassWarning\n",
      "   FormatterWarning\n",
      "  EncodingWarning\n",
      "  DeprecationWarning\n",
      "   ProvisionalWarning\n",
      "  PendingDeprecationWarning\n",
      "  SyntaxWarning\n",
      "  RuntimeWarning\n",
      "   ProactorSelectorThreadWarning\n",
      "   UnknownTimezoneWarning\n",
      "   PEP440Warning\n",
      "  FutureWarning\n",
      "   ProvisionalCompleterWarning\n",
      "  ImportWarning\n",
      "  UnicodeWarning\n",
      "  BytesWarning\n",
      "  ResourceWarning\n",
      "  DeprecatedTzFormatWarning\n",
      "  PkgResourcesDeprecationWarning\n",
      " _OptionError\n",
      " _Error\n",
      " error\n",
      " Verbose\n",
      " Error\n",
      " SubprocessError\n",
      "  CalledProcessError\n",
      "  TimeoutExpired\n",
      " TokenError\n",
      " StopTokenizing\n",
      " ClassFoundException\n",
      " EndOfBlock\n",
      " TraitError\n",
      " Error\n",
      " Error\n",
      "  CancelledError\n",
      "  TimeoutError\n",
      "  InvalidStateError\n",
      " _GiveupOnSendfile\n",
      " error\n",
      " Incomplete\n",
      " TimeoutError\n",
      " InvalidStateError\n",
      " LimitOverrunError\n",
      " QueueEmpty\n",
      " QueueFull\n",
      " error\n",
      " LZMAError\n",
      " RegistryError\n",
      " _GiveupOnFastCopy\n",
      " Empty\n",
      " Full\n",
      " ZMQBaseError\n",
      "  ZMQError\n",
      "   ContextTerminated\n",
      "   Again\n",
      "   InterruptedSystemCall\n",
      "  ZMQBindError\n",
      "  NotDone\n",
      " PickleError\n",
      "  PicklingError\n",
      "  UnpicklingError\n",
      " _Stop\n",
      " ArgumentError\n",
      " ArgumentTypeError\n",
      " ConfigError\n",
      "  ConfigLoaderError\n",
      "   ArgumentError\n",
      "  ConfigFileNotFound\n",
      " ConfigurableError\n",
      "  MultipleInstanceError\n",
      " ApplicationError\n",
      " TimeoutError\n",
      " ArgumentError\n",
      " COMError\n",
      " ReturnValueIgnoredError\n",
      " KeyReuseError\n",
      " UnknownKeyError\n",
      " LeakedCallbackError\n",
      " BadYieldError\n",
      " ReturnValueIgnoredError\n",
      " Return\n",
      " InvalidPortNumber\n",
      " NoIPAddresses\n",
      " BadZipFile\n",
      " LargeZipFile\n",
      " Error\n",
      "  NoSectionError\n",
      "  DuplicateSectionError\n",
      "  DuplicateOptionError\n",
      "  NoOptionError\n",
      "  InterpolationError\n",
      "   InterpolationMissingOptionError\n",
      "   InterpolationSyntaxError\n",
      "   InterpolationDepthError\n",
      "  ParsingError\n",
      "   MissingSectionHeaderError\n",
      " BadEntryPoint\n",
      " NoSuchEntryPoint\n",
      " DuplicateKernelError\n",
      " ErrorDuringImport\n",
      " NotOneValueFound\n",
      " CannotEval\n",
      " OptionError\n",
      " BdbQuit\n",
      " Restart\n",
      " FindCmdError\n",
      " HomeDirError\n",
      " ProfileDirError\n",
      " IPythonCoreError\n",
      "  TryNext\n",
      "  UsageError\n",
      "  StdinNotImplementedError\n",
      " InputRejected\n",
      " GetoptError\n",
      " ErrorToken\n",
      " PrefilterError\n",
      " AliasError\n",
      "  InvalidAliasError\n",
      " Error\n",
      "  InterfaceError\n",
      "  DatabaseError\n",
      "   InternalError\n",
      "   OperationalError\n",
      "   ProgrammingError\n",
      "   IntegrityError\n",
      "   DataError\n",
      "   NotSupportedError\n",
      " Warning\n",
      " SpaceInInput\n",
      " DOMException\n",
      "  IndexSizeErr\n",
      "  DomstringSizeErr\n",
      "  HierarchyRequestErr\n",
      "  WrongDocumentErr\n",
      "  InvalidCharacterErr\n",
      "  NoDataAllowedErr\n",
      "  NoModificationAllowedErr\n",
      "  NotFoundErr\n",
      "  NotSupportedErr\n",
      "  InuseAttributeErr\n",
      "  InvalidStateErr\n",
      "  SyntaxErr\n",
      "  InvalidModificationErr\n",
      "  NamespaceErr\n",
      "  InvalidAccessErr\n",
      "  ValidationErr\n",
      " ValidationError\n",
      " EditReadOnlyBuffer\n",
      " _Retry\n",
      " InvalidLayoutError\n",
      " HeightIsUnknownError\n",
      " GuardRejection\n",
      " ParserSyntaxError\n",
      " InternalParseError\n",
      " _PositionUpdatingFinished\n",
      " SimpleGetItemNotFound\n",
      " UncaughtAttributeError\n",
      " HasNoContext\n",
      " ParamIssue\n",
      " _JediError\n",
      "  InternalError\n",
      "  WrongVersion\n",
      "  RefactoringError\n",
      " OnErrorLeaf\n",
      " InvalidPythonEnvironment\n",
      " MessageError\n",
      "  MessageParseError\n",
      "   HeaderParseError\n",
      "   BoundaryError\n",
      "  MultipartConversionError\n",
      "  CharsetError\n",
      " Error\n",
      " HTTPException\n",
      "  NotConnected\n",
      "  InvalidURL\n",
      "  UnknownProtocol\n",
      "  UnknownTransferEncoding\n",
      "  UnimplementedFileMode\n",
      "  IncompleteRead\n",
      "  ImproperConnectionState\n",
      "   CannotSendRequest\n",
      "   CannotSendHeader\n",
      "   ResponseNotReady\n",
      "  BadStatusLine\n",
      "   RemoteDisconnected\n",
      "  LineTooLong\n",
      " InteractivelyDefined\n",
      " KillEmbedded\n",
      " Error\n",
      "  NoSuchProcess\n",
      "   ZombieProcess\n",
      "  AccessDenied\n",
      "  TimeoutExpired\n",
      " Error\n",
      " TimeoutExpired\n",
      " TimeoutAbandoned\n",
      " QueueEmpty\n",
      " QueueFull\n",
      " ExpatError\n",
      " Error\n",
      "  ProtocolError\n",
      "  ResponseError\n",
      "  Fault\n",
      " error\n",
      " com_error\n",
      " internal_error\n",
      " ParseBaseException\n",
      "  ParseException\n",
      "  ParseFatalException\n",
      "   ParseSyntaxException\n",
      " RecursiveGrammarException\n",
      " ResolutionError\n",
      "  VersionConflict\n",
      "   ContextualVersionConflict\n",
      "  DistributionNotFound\n",
      "  UnknownExtra\n",
      " UnableToResolveVariableException\n",
      " InvalidTypeInArgsException\n",
      " ParseError\n",
      " EndMarkerReached\n"
     ]
    }
   ],
   "source": [
    "python_exception_hierarchy(Exception)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8be13673",
   "metadata": {},
   "source": [
    "**Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.**\n",
    "\n",
    "The ArithmeticError class is a base class for exceptions that occur during arithmetic operations. It serves as a parent class for several more specific arithmetic-related exception classes. Here are two exceptions that are defined within the ArithmeticError class hierarchy:\n",
    "\n",
    "- ZeroDivisionError:\n",
    "  This exception is raised when an attempt is made to divide a number by zero.\n",
    "  \n",
    "- OverflowError:\n",
    "  This exception is raised when an arithmetic operation exceeds the limits of the data type or platform's representational range."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "76afdf23",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "#ZeroDividionError\n",
    "try:\n",
    "    print(100/0)\n",
    "except ZeroDivisionError as z:\n",
    "    print(\"Error:\",z)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a568fff2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "OverflowError: math range error\n"
     ]
    }
   ],
   "source": [
    "#overflowError\n",
    "import math\n",
    "\n",
    "try:\n",
    "    result = math.exp(1000)\n",
    "except OverflowError as e:\n",
    "    print(\"OverflowError:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3364c778",
   "metadata": {},
   "source": [
    "**Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.**\n",
    "\n",
    "The LookupError class in Python is a base class for exceptions that occur when trying to access a collection of items (such as a list, dictionary, or sequence) using an invalid key or index. It is a subclass of the built-in Exception class and serves as a parent class for more specific lookup-related exceptions like KeyError and IndexError.\n",
    "\n",
    "Here's an explanation of KeyError and IndexError along with examples:\n",
    "\n",
    "- KeyError:\n",
    "  The KeyError is raised when you try to access a dictionary with a key that doesn't exist in the dictionary.\n",
    "  \n",
    "- IndexError:\n",
    "  The IndexError is raised when you try to access an index that is out of the valid range of indices for a sequence (like a list or a string)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1ec2a77a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "KeyError: 'sai'\n"
     ]
    }
   ],
   "source": [
    "#KeyError\n",
    "my_dict = {'a':123,'cd':\"abc\",3:6}\n",
    "try:\n",
    "    my_dict[\"sai\"]\n",
    "except KeyError as k:\n",
    "    print(\"KeyError:\",k)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "3d125ef9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "IndexError: list index out of range\n"
     ]
    }
   ],
   "source": [
    "#IndexError\n",
    "my_list = [1,33,4,553,3333]\n",
    "try:\n",
    "    my_list[7]\n",
    "except IndexError as i:\n",
    "    print(\"IndexError:\",i)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "55a3bee6",
   "metadata": {},
   "source": [
    "**Q5. Explain ImportError. What is ModuleNotFoundError?**\n",
    "\n",
    "In Python, ImportError and ModuleNotFoundError are both exceptions that occur when you encounter issues related to importing modules or packages.\n",
    "\n",
    "- ImportError:\n",
    "  ImportError is a base class for exceptions related to importing modules. It is raised when there is a problem importing a module, which could be due to various reasons such as a missing module, circular imports, or issues within the imported module itself.\n",
    "  \n",
    "- ModuleNotFoundError:\n",
    "  ModuleNotFoundError is a subclass of ImportError that is specifically raised when the Python interpreter is unable to locate the module you're trying to import."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c5a66475",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ImportError: cannot import name 'non_exist_method' from 'math' (unknown location)\n"
     ]
    }
   ],
   "source": [
    "#ImportError\n",
    "try:\n",
    "    from math import non_exist_method\n",
    "except ImportError as i:\n",
    "    print(\"ImportError:\",i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "440cefb4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ModuleNotFoundError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "#ModuleNotFoundError\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError as m:\n",
    "    print(\"ModuleNotFoundError:\",m)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8a856f2c",
   "metadata": {},
   "source": [
    "**Q6. List down some best practices for exception handling in python.**\n",
    "\n",
    "Exception handling is an important aspect of writing robust and maintainable Python code. Here are some best practices for effective exception handling in Python:\n",
    "\n",
    "- Use Specific Exception Types:\n",
    "  Catch specific exception types rather than using a generic Exception. This helps you handle different types of errors more precisely.\n",
    "\n",
    "- Avoid Bare except:\n",
    "  Avoid using bare except statements without specifying the exception type. This can hide bugs and make debugging difficult. Always specify the exception you're expecting to handle.\n",
    "\n",
    "- Use Try-Except Blocks Sparingly:\n",
    "  Don't use try-except blocks for every line of code. Use them only around the specific statements that might raise exceptions.\n",
    "\n",
    "- Handle Exceptions Locally:\n",
    "  Handle exceptions as close to the source of the problem as possible. This makes it easier to determine the cause of the exception.\n",
    "\n",
    "- Separate Exception Handling from Business Logic:\n",
    "  Keep your exception handling separate from your main business logic. This makes your code more readable and maintainable.\n",
    "\n",
    "- Use finally for Cleanup:\n",
    "  Use the finally block to ensure that cleanup code (like closing files or releasing resources) is executed regardless of whether an exception occurred or not.\n",
    "\n",
    "- Provide Clear Error Messages:\n",
    "  When raising exceptions or printing error messages, be clear about what went wrong and how to resolve it. This helps users of your code understand the issue.\n",
    "\n",
    "- Log Exceptions:\n",
    "  Use logging to capture exceptions and relevant context information. This aids in troubleshooting and diagnosing issues.\n",
    "\n",
    "- Document Exception Handling:\n",
    "  Document the exceptions that can be raised by your functions and methods. This helps users of your code understand how to handle them."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
